### ISSUE TITLE
Config#update does not return self

### ISSUE THREAD

**Issue by travisdahlke** [dry-rb/dry-configurable#90]
**Describe the bug**

Since upgrading to 0.11.3, config#update does not return self.
```
NoMethodError: undefined method `test' for {}:Hash
```

**To Reproduce**

```rb
require 'dry-configurable'

class App
  include Dry::Configurable
  setting :foo
end

app = App.new

config = app.config.update(foo: 'bar')
puts config.foo
# => undefined method `foo' for {:foo=>"bar"}:Hash
```

**Expected behavior**

Should return the config object as [documented](https://rubydoc.info/gems/dry-configurable/Dry%2FConfigurable%2FConfig:update) and as 0.8 did.
```rb
require 'dry-configurable'

class App
  include Dry::Configurable
  setting :foo
end

app = App.new

config = app.config.update(foo: 'bar')
puts config.foo
# => bar
```

**Your environment**

- Affects my production application: No
- Ruby version: 2.6.5
- OS: Mac

**Comment by esparta** [comment]
I think this should be closed it was effectively fixed on 0.11.4
