### ISSUE TITLE
0.16.0 breaks Sinatra config_file

### ISSUE THREAD

**Issue by DawidJanczak** [dry-rb/dry-configurable#148]
## Describe the bug

After upgrading this library to 0.16.0 the config_file extension in Sinatra seems to break with
```
undefined method `foo' for Sinatra::Application:Class
```

when `settings.foo` gets called.

This was working just fine on 0.15.0.

I thought it might be zeitwerk, but 0.15.0 + zeitwerk work just fine so I suspect it's the changes in version 0.16.0 (possibly _related to_ zeitwerk). Also this only seems to be happening in our tests in RSpec, not in normal dev environment.

## To Reproduce

Install sinatra, sinatra-contrib and configure config_file extension. Let me know if you need a reproduction repository, I can prepare something later today or tomorrow.

## Expected behavior

`settings.foo` from Sinatra should not crash.

## My environment

- Affects my production application: **YES**
- Ruby version: 3.1.2
- OS: docker image, alpine 3.15

**Comment by timriley** [comment]
Hi @DawidJanczak, I'd definitely appreciate a reproduction in code, I'm not particularly familiar with details like this from Sinatra.

**Comment by DawidJanczak** [comment]
Hope this helps @timriley : https://github.com/DawidJanczak/dry-configurable-sinatra

Perhaps let's start with the branch that's working, if you checkout `configurable-0.15` (https://github.com/DawidJanczak/dry-configurable-sinatra/compare/configurable-0.15) and run `bundle` followed by `APP_ENV=test bundle exec rspec` it will work just fine.

Now if you check out `main` and again run `bundle` followed by `APP_ENV=test bundle exec rspec` you will notice it's failing. If however you remove the `dry/configurable` require it's working again.

I have to say this is one bizarre situation! I'm almost certain zeitwerk is at fault here, but I don't know enough about it to comment.

**Comment by timriley** [comment]
@DawidJanczak This is extremely weird. I'm officially flummoxed. The two gems don't _seem_ like they should be interacting at all here. dry-configurable certainly doesn't do anything outside of its own `Dry::Configurable` namespace.

I tried changing the `require "dry/configurable"` line in your reproduction to some more specific requires, like `"dry/configurable/config"` and `"dry/configurable/settings"`. Neither of them cause the issue, so whatever it is must be coming from the `dry/configurable.rb` file specifically (which does possibly hint at a Zeitwerk-related issue).

I was chatting with @solnic and he mentioned he might check with @rkh for his thoughts here from a Sinatra perspective.

**Comment by timriley** [comment]
I did one further test. I updated the Gemfile to point to a local checkout of dry-configurable (current main branch). And then I tried commenting out various parts in `lib/dry/configurable.rb` to see what was triggering the actual error.

If I comment out these three lines from the file, then the error goes away:

1. `require "zeitwerk"`
2. `require "dry/core"`
3. loader.setup

**Comment by timriley** [comment]
OK, I boiled it down further.

If you remove dry-configurable from the `Gemfile` and replace it with zeitwerk:

```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'zeitwerk'
gem 'sinatra'
gem 'sinatra-contrib'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
end
```

And change `app.rb` so it requires zeitwerk only:

```
# frozen_string_literal: true

require "zeitwerk"

require 'sinatra'
require 'sinatra/config_file'

config_file '../config.yml'

get '/' do
  p Sinatra::Base.environment
  p settings.foo
end
```

Then the tests still fail in the same way.

This makes me think this is **a problem between sinatra/sinatra-contrib and zeitwerk only.**

My feeling is you happened to see it through dry-configurable because it was the first gem upgrade that introduced zeitwerk into your bundle.

**Comment by timriley** [comment]
I've also determined that this comes from Zeitwerk's replacement of `Kernel#require`. If you `bundle open zeitwerk` and comment out everything inside its `lib/zeitwerk/kernel.rb`, then the rests begin passing again.

I'm sure this is only the first step of several to figuring out what's going on here, but hopefully it helps :)

**Comment by DawidJanczak** [comment]
Thanks @timriley, that is really helpful! I'll test this later and file an issue with Sinatra or Zeitwerk :)

**Comment by fxn** [comment]
Hey!

I'll have a look. Definitely seems like some kind of conflict between Zeitwerk and Sinatra. Interestingly, if you load Zeitwerk _after_ Sinatra, the test passes.

Let me see if I find the root cause, then we might follow in the affected repo.

**Comment by DawidJanczak** [comment]
Thanks @fxn, but I already opened an issue here https://github.com/sinatra/sinatra/issues/1826 Do let me know if you'd rather have that closed for now, if not I'll leave it open.
